workspace:
  base: /data/
  path: /

services:
  - name: etcd
    image: quay.io/coreos/etcd:latest
    ports:
      - 2379:2379
      - 2380:2380
    command: "/usr/local/bin/etcd --data-dir=/etcd-data --name node --initial-advertise-peer-urls
        http://127.0.0.1:2380 --listen-peer-urls http://127.0.0.1:2380 --advertise-client-urls
        http://127.0.0.1:2379 --listen-client-urls http://127.0.0.1:2379 --initial-cluster
        node=http://127.0.0.1:2380"
    restart:
      policy: "always"

pipeline:
  - image: golang:stretch
    commands:
      - apt-get -y install openssl
      - cp /data ${GOAPTH}/src/github.com/unloop/lastbackend
      - cd ${GOAPTH}/src/github.com/unloop/lastbackend
      - make deps
      - make test
    when:
      event: [push, pull_request, tag]
  - image: build:hub.lstbknd.net/unloop/lastbackend:master
    commands:
      - entrypoint build -i hub.lstbknd.net/unloop/lastbackend:master -f ./images/lastbackend/Dockerfile .
      - entrypoint push hub.lstbknd.net/unloop/lastbackend:master
    when:
      event: [push, pull_request, tag]
  - image: build:hub.lstbknd.net/unloop/lastbackend:master
    commands:
      - entrypoint build -i hub.lstbknd.net/unloop/discovery:master -f ./images/discovery/Dockerfile .
      - entrypoint push hub.lstbknd.net/unloop/discovery:master
    when:
      event: [push, pull_request, tag]
  - image: build:hub.lstbknd.net/unloop/lastbackend:master
    commands:
      - entrypoint build -i hub.lstbknd.net/unloop/ingress:master -f ./images/ingress/Dockerfile .
      - entrypoint push hub.lstbknd.net/unloop/ingress:master
    when:
      event: [push, pull_request, tag]
  - image: build:hub.lstbknd.net/unloop/lastbackend:master
      commands:
        - entrypoint build -i hub.lstbknd.net/unloop/exporter:master -f ./images/exporter/Dockerfile .
        - entrypoint push hub.lstbknd.net/unloop/exporter:master
    when:
      event: [push, pull_request, tag]

registry:
  - name: lastbackend
    settings:
      auto_tag: true
      dockerfile: "./images/lastbackend/Dockerfile"
    when:
      event:
        - push
        - tag
  - name: discovery
    settings:
      auto_tag: true
      dockerfile: "./images/discovery/Dockerfile"
    when:
      event:
        - push
        - tag
  - name: ingress
    settings:
      auto_tag: true
      dockerfile: "./images/ingress/Dockerfile"
    when:
      event:
        - push
        - tag
  - name: exporter
    settings:
      auto_tag: true
      dockerfile: "./images/exporter/Dockerfile"
    when:
      event:
        - push