---
# Runtime
verbose: 3
token: lstbknd
api:
  uri: "api.lbdp.io:2967"
  tls:
    insecure: true
    ca: "/opt/cert/lastbackend/ca.pem"
    cert: "/opt/cert/lastbackend/client.pem"
    key: "/opt/cert/lastbackend/client-key.pem"

node:
  host: 0.0.0.0
  port: 2969
  tls:
    insecure: true
    ca: "/opt/cert/node/ca.pem"
    server_cert: "/opt/cert/node/server.pem"
    server_key: "/opt/cert/node/server-key.pem"
    client_cert: "/opt/cert/node/client.pem"
    client_key: "/opt/cert/node/client-key.pem"
  logs:
    driver: "lastbackend"
    collector: "api.lbdp.io:2963"

# Runtime
runtime:
  interface: "ens3" #external interface to route traffic
  docker:
    version: 1.35
  cri:
    type: "docker"
  #    tls:
  #      ca_file: ""
  #      cert_file: ""
  #      key_file: ""
  iri:
    type: "docker"
  #    tls:
  #      ca_file: ""
  #      cert_file: ""
  #      key_file: ""
  cni:
    type: "vxlan"
  cpi:
    type: "ipvs"
  csi:
    dir:
      root: "/var/lib/lastbackend/"